const actionTypes = {
    SET_INITIAL_SATE: 'SET_INITIAL_SATE',

    // login
    SET_LOGIN_INITIAL_STATE: 'SET_LOGIN_INITIAL_STATE',
    SET_LOGIN: 'SET_LOGIN',

    // user
    SET_USER_INITIAL_STATE: 'SET_USER_INITIAL_STATE',
    SET_USER: 'SET_USER',

    // sign up
    SET_SIGN_UP_INITIAL_STATE: 'SET_SIGN_UP_INITIAL_STATE',
    SET_SIGN_UP: 'SET_SIGN_UP',

    // publications
    SET_PUBLICATIONS_INITIAL_STATE: 'SET_PUBLICATIONS_INITIAL_STATE',
    SET_PUBLICATIONS: 'SET_PUBLICATIONS',

    // coments
    SET_PUBLICATIONS_COMENTS: 'SET_PUBLICATIONS_COMENTS',
}

export { actionTypes }