const actionTypes = {
    SET_INITIAL_SATE: 'SET_INITIAL_SATE',

    // login
    SET_LOGIN_INITIAL_STATE: 'SET_LOGIN_INITIAL_STATE',
    SET_LOGIN: 'SET_LOGIN',

    // user
    SET_USER_INITIAL_STATE: 'SET_USER_INITIAL_STATE',
    SET_USER: 'SET_USER',

    // edit user
    SET_EDIT_USER_INITIAL_STATE: 'SET_EDIT_USER_INITIAL_STATE',
    SET_EDIT_USER: 'SET_EDIT_USER',

    // sign up
    SET_SIGN_UP_INITIAL_STATE: 'SET_SIGN_UP_INITIAL_STATE',
    SET_SIGN_UP: 'SET_SIGN_UP',

    // publications
    SET_PUBLICATIONS_INITIAL_STATE: 'SET_PUBLICATIONS_INITIAL_STATE',
    SET_PUBLICATIONS: 'SET_PUBLICATIONS',

    // publications resume
    SET_PUBLICATIONS_RESUME_INITIAL_STATE: 'SET_PUBLICATIONS_RESUME_INITIAL_STATE',
    SET_PUBLICATIONS_RESUME: 'SET_PUBLICATIONS_RESUME',

    // coments
    SET_PUBLICATIONS_COMENTS: 'SET_PUBLICATIONS_COMENTS',

    // new publication
    SET_NEW_PUBLICATION_INITIAL_STATE: 'SET_NEW_PUBLICATION_INITIAL_STATE',
    SET_NEW_PUBLICATION: 'SET_NEW_PUBLICATION',

    // theme
    SET_THEME_LIGHT: 'SET_THEME_LIGHT',
    SET_THEME_DARK: 'SET_THEME_DARK',
}

export { actionTypes }